openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://localhost:8080/
paths:
  /rates:
    $ref: "./resources/ratesResources.yml"
  /rates/{id}:
    $ref: "./resources/ratesIdResources.yml"
