DROP TABLE IF EXISTS T_RATES;

CREATE TABLE IF NOT EXISTS T_RATES (
    ID SERIAL PRIMARY KEY NOT NULL,
    BRAND_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    PRICE INT NOT NULL,
    CURRENCY_CODE VARCHAR(3) NOT NULL
);

CREATE INDEX IF NOT EXISTS rates_brand_id_index ON T_RATES USING btree (brand_id);
CREATE INDEX IF NOT EXISTS rates_product_id_index ON T_RATES USING btree (product_id);
CREATE INDEX IF NOT EXISTS rates_currency_code_index ON T_RATES USING btree (currency_code);